#########################################
#  Messages de Bienvenue pour les joueurs non staff       
#                     ( a mettre entre " " )                        
#                                                                                                  
#                                                                                                  
#########################################
normal-player-1: "&7Bienvenue !"
normal-player-2: "&7Bienvenue !"
normal-player-3: "&7Bienvenue !"
normal-player-4: "&7Bienvenue !"
normal-player-5: "&7Bienvenue !"


#########################################
#  Messages de Bienvenue pour les membres du staff      
#                         ( fonctionne aussi pour les OPs)                
#                                                                                                  
#                                                                                                  
#########################################
staff-player-1: "&eBienvenue !"
staff-player-2: "&eBienvenue, fais /warp a > /sell et /rankup !"
staff-player-3: "&eBienvenue, passe un agréable moment sur notre serveur !"
staff-player-4: "&eBienvenue jeune mineur !"
staff-player-5: "&eBienvenue, fais /aide opprison ou /tuto !"


#########################################
#  																						        
#                         le bloc du LuckyBlock       					    
#                             (en "DIAMOND_ORE" par ex)   
#
#           Id du bloc par défaut: 153               
#                                                                                                  
#########################################

luckyblock: "QUARTZ_ORE" #TokenEnchantBlock

#########################################
#  																						             
#                         les loots LuckyBlocks, TokenEnchantZone             					  
#                             (en "DIAMOND_ORE" par ex)                 
#                                                                                                  
#########################################
loot-1: 1  #Chiffre = le nbr de token give
loot-2: 3  #Chiffre = le nbr de token give
loot-3: 5  #Chiffre = le nbr de token give
loot-4: 8  #Chiffre = le nbr de token give
loot-5: 10  #Chiffre = le nbr de token give
loot-6: 12  #Chiffre = le nbr de token give
loot-7: 15  #Chiffre = le nbr de token give
loot-8: 10  #Chiffre = le nbr de token give
loot-9: 25  #Chiffre = le nbr de token give
loot-10: 50  #Chiffre = le nbr de token give
loot-11: 75  #Chiffre = le nbr de token give
loot-12: 100  #Chiffre = le nbr de token give
loot-13: 60  #Chiffre = le nbr de token give
loot-14: 30  #Chiffre = le nbr de token give
loot-15: 94  #Chiffre = le nbr de token give



###########################################
#  																						             
#                         les commandes LuckyBlocks              					  
#        commande custom = commande de customisation        
#   commande d'action = commande exercer par le serveur 
#  comme le te add, par exemple                                      
#                                                   
###########################################


cmd-add1: "te add"                   #commande custom 1
cmd-replace-add1: "te add"            #commande d'action 1

cmd-add2: "te add"                    #commande custom 2
cmd-replace-add2: "te add"             #commande d'action 2

cmd-add3: "te add"                   #commande custom 3
cmd-replace-add3: "te add"            #commande d'action 3

cmd-add4: "te add"                  #commande custom 4
cmd-replace-add4: "te add"             #commande d'action 4

cmd-add5: "te add"                   #commande custom 5
cmd-replace-add5: "te add"             #commande d'action 5

cmd-add6: "te add"                  #commande custom 6
cmd-replace-add6: "te add"            #commande d'action 6

cmd-add7: "te add"                   #commande custom 7
cmd-replace-add7: "te add"            #commande d'action 7

cmd-add8: "p give"                   #commande custom 8
cmd-replace-add8: "p give"            #commande d'action 8

cmd-add9: "p give"                   #commande custom 9
cmd-replace-add9: "p give"            #commande d'action 19

cmd-add10: "p give"                  #commande custom 10
cmd-replace-add10: "p give"           #commande d'action 10

cmd-add11: "p give"                  #commande custom 11
cmd-replace-add11: "p give"           #commande d'action 11

cmd-add12: "p give"                  #commande custom 12
cmd-replace-add12: "p give"           #commande d'action 12

cmd-add13: "p give"                  #commande custom 13
cmd-replace-add13: "p give"           #commande d'action 13

cmd-add14: "p give"                  #commande custom 14
cmd-replace-add14: "p give"           #commande d'action 14

cmd-add15: "p give"                  #commande custom 15
cmd-replace-add15: "p give"           #commande d'action 15
##################
chat:
  prefix: '@' 
  #pareil qu'en jeu

  format: '&6STAFF &r> &5%name &r> %chat' 
  #msg de syntaxe

  sound: true 
  #true false pr savoir si tu veux un son ou pas


